name: Trigger auto deployment for bitethebookie-app-20260216193644

on:
  push:
    branches: [ master ]
    paths:
      - '**'
      - '.github/workflows/bitethebookie-app-20260216193644-AutoDeployTrigger-40efce92-078a-4a45-83fd-9edbbcef2484.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Docker version (for debugging)
        run: docker version

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: bitethebookie20260216193956.azurecr.io
          username: ${{ secrets.BITETHEBOOKIEAPP20260216193644_REGISTRY_USERNAME }}
          password: ${{ secrets.BITETHEBOOKIEAPP20260216193644_REGISTRY_PASSWORD }}

      - name: Build and push image (Dockerfile)
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: bitethebookie20260216193956.azurecr.io/bitethebookie-app-20260216193644:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BITETHEBOOKIEAPP20260216193644_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BITETHEBOOKIEAPP20260216193644_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BITETHEBOOKIEAPP20260216193644_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: bitethebookie-app-20260216193644
          resourceGroup: BiteTheBookie
          registryUrl: bitethebookie20260216193956.azurecr.io
          registryUsername: ${{ secrets.BITETHEBOOKIEAPP20260216193644_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BITETHEBOOKIEAPP20260216193644_REGISTRY_PASSWORD }}
          imageToDeploy: bitethebookie20260216193956.azurecr.io/bitethebookie-app-20260216193644:${{ github.sha }}