name: Trigger auto deployment for bitethebookie-appv2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/bitethebookie-appv2-AutoDeployTrigger-37130e9e-c228-4fc6-9692-0c98132da0a1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BITETHEBOOKIEAPPV2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BITETHEBOOKIEAPPV2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BITETHEBOOKIEAPPV2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: bitebookiebettingodds.azurecr.io
          registryUsername: ${{ secrets.BITETHEBOOKIEAPPV2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BITETHEBOOKIEAPPV2_REGISTRY_PASSWORD }}
          containerAppName: bitethebookie-appv2
          resourceGroup: BiteTheBookie_RG
          imageToBuild: bitebookiebettingodds.azurecr.io/bitethebookie-appv2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


