on:
  push:
    branches:
    - master
permissions:
  id-token: write
  contents: read
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: bitethebookie-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: BiteTheBookie-env-20251211193856
  RESOURCE_GROUP: BiteTheBookie_RG
  CONTAINER_REGISTRY_NAME: bitethebookie20251211194253
  CONTAINER_REGISTRY_LOGIN_SERVER: bitethebookie20251211194253.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.BiteTheBookie_env_20251211193856_CLIENT_ID_2CA4 }}
        tenant-id: ${{ vars.BiteTheBookie_env_20251211193856_TENANT_ID_2CA4 }}
        subscription-id: ${{ vars.BiteTheBookie_env_20251211193856_SUBSCRIPTION_ID_2CA4 }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.BiteTheBookie20251211194253_USERNAME_2CA4 }}
        acrPassword: ${{ secrets.BiteTheBookie20251211194253_PASSWORD_2CA4 }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
